### ISSUE TITLE
Implementing stage

### ISSUE THREAD

**Issue by simonmoulds** [Ryan-Riggs/RivRetrieve#1]
Hi Ryan,

I've started to implement the stage retrieval methods. One design question is whether to use the same function for all variables available via the respective APIs. E.g. `australia()` could be written as:

```R
australia <- function(site,
                      variable = "stage",
                      start_date = NULL,
                      end_date = NULL,
                      ...) {

  if (is.null(start_date))
    start_date <- "1900-01-01"

  if (is.null(end_date))
    end_date <- Sys.time() %>%
      as.Date() %>%
      format("%Y-%m-%d")

  ## Recode variables from RivRetrieve convention to BoM convention
  if (variable == "stage") {
    variable <- "Water Course Level"
  } else if (variable == "discharge") {
    variable <- "Water Course Discharge"
  } else {
    stop(sprintf("Variable %s is not available", variable))
  }
  data <- try(get_daily(variable, site, start_date, end_date))
  if (inherits(data, "try-error"))
    next
  data <- data %>%
    mutate(Variable = variable, .before = Value) %>%
    mutate(Timestamp = as.Date(Timestamp))
  return(data)
}
```

Another question this raises is whether to implement a custom vocabulary for the variables within RivRetrieve. The idea would be to abstract the requirements of the specific API so that users can supply either `stage` or `discharge` to each API wrapper. 

Let me know your thoughts! 

Simon

**Comment by Ryan-Riggs** [comment]
Hi Simon,

I think your idea of using the same function for each agency and requiring the user to input whether they want stage or discharge is a great idea! I also think this helps align our functions with how the dataRetrieval package operates. 

That being said, I haven't tried to access stage data so I'm unsure of how similar the process is between scraping discharge data and scraping stage data.

**Comment by simonmoulds** [comment]
Great - I'll have a look at this. So far I've developed stage methods for Australia and Brazil - I'll carry on working through the various agencies. 

I don't think it matters if some agencies don't provide stage - we can just provide a helpful error message to tell the user that the variable is not available. In any case, let's see what comes up as we work through the functions.

**Comment by Ryan-Riggs** [comment]
Sounds great! Let me know how I can help out. If you share some of the stage scripts with me, I could try to add them into the discharge functions.

**Comment by simonmoulds** [comment]
I think I've added stage to all existing functions now. Only `chile` and `france` return an error message if the user attempts to download stage, as I don't think this data is readily available for these two countries. 

I may well have broken some things along the way, so I will now try and identify/fix these.
