### ISSUE TITLE
Site data

### ISSUE THREAD

**Issue by simonmoulds** [Ryan-Riggs/RivRetrieve#10]
At present the metadata containing site information for the respective countries is stored as package level data. This means that to update the list of sites (e.g. if a new site is added or a site becomes unavailable) a new package version has to be created. In most cases (not all) the list of sites can be downloaded. I suggest we create a set of hidden functions to access (and potentially download) the site data. These hidden functions could be called from the existing set of functions by introducing an argument (default `sites=FALSE`). Then if the user passed something like:

```{r}
sites <- australia(sites = TRUE, variable = "discharge")
```
They would get the list of sites with discharge data for Australia. An alternative would be to create its own function - 

```{r}
sites <- australia_sites(variable = "discharge")
```
But I prefer the first option, as it means that users only have to learn one function pattern. 

To begin with I would suggest we only return the data that you have already preloaded, but hide this data from the user so they cannot load it themselves (i.e. by doing `data("australia")`). Later on we can update the functions to download the data and cache it for later use. 

What do you think?

**Comment by Ryan-Riggs** [comment]
Thanks for bringing this up. I agree that the first option makes the most sense so that the user only needs to learn one function pattern. I also agree that for now, we could just limit this to the data we have already loaded into the package. Do you know how we go about making the preloaded data accessible via functions only?

**Comment by simonmoulds** [comment]
I've just sent PR #12 which trials the above approach. Try `australia(sites = TRUE)`. To hide data from the user you just save it all in `R/sysdata.rda`. 

Let me know if you think this approach is a good one.
