### ISSUE TITLE
QA/QC

### ISSUE THREAD

**Issue by Ryan-Riggs** [Ryan-Riggs/RivRetrieve#17]
@simonmoulds Just moving our email conversation over to here. A quick and easy test for stage could be to require a positive correlation between same-day stage and discharge at a certain number of randomly selected gauges for each agency. Do you have any thoughts or additional ideas that we could do?

**Comment by Ryan-Riggs** [comment]
A potential option for confirming discharge units/accuracy is to do the following for each agency:

1. Calculate the distance between all agency stations and the GRDC stations. 
2. Identify redundant gauges (being in both the agency and GRDC databases) as distances of less than 10-m. 
3. Limit the following steps to 10 random gauges.
4. Merge the agency timeseries and GRDC timeseries.
5. Calculate mean error and mean percent error between the two datasets for each gauge location.

**Comment by simonmoulds** [comment]
@Ryan-Riggs - yes, this is a good option but would require quite a lot of data. In our group we have been able to link several thousand streamflow datasets to the GSIM dataset (https://essd.copernicus.org/articles/10/765/2018/), which might be able to provide some reference data to verify units etc.

**Comment by Ryan-Riggs** [comment]
@simonmoulds Yeah I think GSIM is a good option. I have a script to scrape the GRDC so the steps outlined above can be automated. I can email it to you.
